version: "3"
services:
  app:
    container_name: omics-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
      - "8080:8080"
    volumes:
      - ./src:/usr/src/app/src
    command: ["node", "--inspect=0.0.0.0:3001", "dist/app.js"]
    environment:
      NODE_ENV: development
      DB_CONN_STRING: "mongodb://mongoDb:27017"
      DB_NAME: "omics"
      MOCK_DATA_PATH: "./mocking.csv"
      MONGO_USERNAME: admin
      MONGO_PASSWORD: interview
      HTTP_PORT: 8080
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: mongoDb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: interview
